# program to demonstrate arithmetic operators
a = int(input("enter first number : "))
b = int(input("enter second number : "))
print(a + b)
print(a - b)
print(a * b)
print(a ** b)
print(a / b)
print(a // b)
print(a % b)
